name: Build & Docker image Push

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 체크아웃
    - uses: actions/checkout@v3 

    # JDK version 설정
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # maven 캐싱
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Maven build
    - name: Build with Maven
      run: |
        # 현재위치 테스트
        pwd
        cd ./CornMarket
        ./mvnw clean package
				
    # Docker GitHub 로그인
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:		    
        registry: ghcr.io
        username: hice11		    
        password: ${{ secrets.CR_PAT }}
		    
    # Docker 이미지 build & Github에 push
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.4.1
				
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/hice11/tomcat-server:latest
